#!/usr/bin/python3
"""square area"""


class Square:
    """Class crate  a Square """
    @property
    def size(self):
        """ return a size"""
        return self.__size

    @size.setter
    def size(self, value):
        """get size"""
        self.__size = value

    def area(self):
        """Method that returns the area """
        return self.__size ** 2

    def __init__(self, size=0):
        """ private square constructor and error handling"""

        self.__size = size
        if type(size) != int:
            raise TypeError("size must be an integer ")

        elif size < 0:
            raise ValueError("size must be >= 0")

        def my_print(self, size):
            """comentar"""
            p = 0
            self.p = self.__size:
                if self.p == 0
            print ("n\")
                else